version: "3.6"
volumes:
  mysql_data:
services:
  personal-service:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "${PER_SERVICE_DATABASE_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${PER_SERVICE_DATABASE_SCHEMA}
      - MYSQL_ROOT_PASSWORD=${PER_SERVICE_DATABASE_PASSWORD}
      - MYSQL_USER=${PER_SERVICE_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${PER_SERVICE_DATABASE_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql