spring:
  application:
    name: 'notification-service'
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
    queue:
      name: 'notifications'
    exchange:
      name: 'notifications_exchange'
    key: 'notifications_routing_key'
  mail:
    host: smtp.gmail.com
    port: 587
    username: vogistv@gmail.com
    password: 'drnztlenraszqale'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8000
