version: "3.5"
volumes:
  postgres_data:
services:
  registry-service:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=medicial
      - POSTGRES_PASSWORD=551617
      - POSTGRES_USER=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata