version: "3.6"
volumes:
  postgres_data:
services:
  personal-service:
    image: postgres:16.1
    ports:
      - "${PER_SERVICE_DATABASE_PORT}:5432"
    environment:
      - POSTGRES_DB=${PER_SERVICE_DATABASE_SCHEMA}
      - POSTGRES_PASSWORD=${PER_SERVICE_DATABASE_PASSWORD}
      - POSTGRES_USER=${PER_SERVICE_DATABASE_USERNAME}
      - PGDATA=/var/lib/postgresql/data/mydata/
    volumes:
      - postgres_data:/var/lib/postgresql/data/mydata/