spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
server:
  port: 8901
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka