server:
  port: 8761
spring:
  application:
    name: 'registry-service'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
