server:
  port: 8800
spring:
  application:
    name: 'personal-service'
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${PER_SERVICE_DATABASE_HOST}:${PER_SERVICE_DATABASE_PORT}/${PER_SERVICE_DATABASE_SCHEMA}
    username: ${PER_SERVICE_DATABASE_USERNAME}
    password: ${PER_SERVICE_DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    user: ${PER_SERVICE_DATABASE_USERNAME}
    password: ${PER_SERVICE_DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:postgresql://${PER_SERVICE_DATABASE_HOST}:${PER_SERVICE_DATABASE_PORT}/${PER_SERVICE_DATABASE_SCHEMA}
  docker:
    compose:
      file: personal-service/compose.yaml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
